### PR TITLE
Catch and return the text of Julia errors when formatting

### PR DESCRIPTION
**Pull request by kmsquire**
This should make debugging problems easier going forward.

### CODE REVIEW

**Comment by singularitti** [comment]
Is this just for easier debugging without changing its functionality or fixing #23?

**Comment by kmsquire** [comment]
For debugging.  Without this, it's nearly impossible to know why the command failed.   With this, at least you get the error log.  It does not fix #23, but with this in place, @samuela should be able to provide enough information to fix it.

**Comment by singularitti** [comment]
Ok, I will merge it for your convenience.

**Comment by samuela** [comment]
Would it be possible to put out a new release with this so I can test it?

**Comment by singularitti** [comment]
> Would it be possible to put out a new release with this so I can test it?

Hi, I don't think this is worth for a release: no new feature, no bug fix, just for us to debug. I can build a `vsix` for you, though.

**Comment by singularitti** [comment]
Can you download it from here @samuela? https://github.com/singularitti/vsix

**Pull request merged**
